name: Présentation

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          cp -r css public/css
          cp -r fonts public/fonts
          cp -r images public/images
        uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --to revealjs
            --source document.md
            --output public/presentation.html
