name: Présentation

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          # this will also include README.md
          echo "::set-output name=files::document.md"

      - uses: docker://pandoc/core:2.9
        with:
          args: --to=revealjs --output=public/presentation.html ${{ steps.files_list.outputs.files }}
      - name: copy static files
        run: |
          cp -r css public/css
          cp -r fonts public/fonts
          cp -r images public/images
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
