name: Présentation

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          # this will also include README.md
          echo "::set-output name=files::document.md"

      - uses: docker://pandoc/latex:2.9
        with:
          args: --to=revealjs --output=output/presentation.html ${{ steps.files_list.outputs.files }}
          
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
