name: Présentation

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          echo "::set-output name=files::presentation.md"

      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --to=revealjs
            -s
            --output=public/index.html
            ${{ steps.files_list.outputs.files }}
      - name: copy files
        id: copy_files
        run: |
          cp -r css public/css
          cp -r fonts public/fonts
          cp -r images public/images
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: ./
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./public
